var json = {
  "Institute of Chinese Medical Sciences":{
    "":{
      "(D)Biomedical Sciences":88,
      "(M)Chinese Medicinal Science":64,
      "(M)Medicinal Administration":63,
      "(B)Biomedical Sciences":32,
    },
  },
  "Faculty of Education":{
    "":{
      "(D)Education":14,
      "(P)Postgraduate Certificate in Education":8,
      "(P)Postgraduate Certificate in Education":19,
      "(B)Chinese":121,
      "(B)English":106,
      "(B)Mathematics":18,
      "(B)Pre-Primary Education":117,
      "(B)Primary Education":130,
    },
  },
  "Faculty of Business Administration":{
    "":{
      "(D)Business Administration":27,
      "(D)Database Management and Information System":1,
      "(D)Economics":1,
      "(D)Strategic Management":2,
      "(B)Business Administration":312,
    },
    "Department of Accounting and Information Management":{
      "(B)Accounting":381,
      "(B)Business Information System":1,
      "(B)Electronic Business":62,
    },
    "Department of Finance and Business Economics":{
      "(B)Business Economics":90,
      "(B)Economics and International Finance":4,
      "(B)Financial Controllership":63,
      "(B)Finance":1,
      "(B)Finance":274,
    },
    "Department of Management and Marketing":{
      "(B)Global Business Management":118,
      "(B)Gaming Management":1,
      "(B)Human Resources Management":226,
      "(B)Management":1,
      "(B)Marketing":190,
      "(B)Gaming and Hospitality Management":66,
      "(B)Hospitality and Gaming Management":209,
    },
  },
  "Faculty of Arts and Humanities":{
    "Department of Chinese":{
      "(D)Linguistics/Linguistics":16,
      "(D)Literary Studies/Literary Studies":27,
      "(M)Chinese Studies in Literature Studies":4,
      "(M)Chinese Linguistics":39,
      "(M)Chinese Literature":69,
      "(B)Chinese Language and Literature":61,
      "(B)Chinese Language and Literature":172,
    },
    "Department of English":{
      "(D)Linguistics/Linguistics":14,
      "(D)Literary Studies":5,
      "(D)Philosophy and Religious Studies":6,
      "(M)Applied English":5,
      "(M)English Studies":91,
      "(M)Translation Studies":114,
      "(B)English Studies":54,
      "(B)English Studies":184,
    },
    "Department of Portuguese":{
      "(D)Linguistics/Linguistics":7,
      "(D)Literary Studies":2,
      "(M)Portuguese Language and Culture":32,
      "(B)Portuguese Studies":70,
      "(B)Portuguese Studies":214,
    },
    "Faculty of Business Administration":{
      "(M)Business Administration":183,
      "(M)Accounting":102,
      "(M)Finance":71,
      "(M)International Integrated Resort Management":53,
    },
    "Faculty of Education":{
      "(M)Curriculum and Instruction":65,
      "(M)Educational Administration":26,
      "(M)Early Childhood Education and Child Development":12,
      "(M)Early Childhood Education and Human Development":17,
      "(M)Educational Psychology":22,
      "(M)Physical Education and Sport Studies":45,
      "(M)School Counseling":16,
    },
    "Centre for Japanese Studies":{
      "(B)Japanese Studies":137,
      "(B)Japanese Studies":43,
    },
  },
  "Faculty of Social Sciences":{
    "Department of Communication":{
      "(D)Communication":18,
      "(M)Communication and New Media":79,
      "(B)English Studies":65,
      "(B)Communication":295,
      "(B)Journalism and Public Communication":49,
    },
    "Department of Economics":{
      "(D)Economics":4,
      "(M)Economics":47,
      "(B)Economics":257,
    },
    "Department of Government and Public Administration":{
      "(D)Public Administration":8,
      "(D)Political Science":10,
      "(M)International Relations and Public Policy":74,
      "(M)European Studies":59,
      "(M)Public Administration":136,
      "(B)Public Administration":2,
      "(B)Government and Public Administration":300,
    },
    "Department of History":{
      "(D)History":14,
      "(M)History":44,
      "(B)History":114,
    },
    "Department of Psychology":{
      "(D)Psychology":11,
      "(M)Clinical Psychology":15,
      "(B)Psychology":155,
    },
    "Department of Sociology":{
      "(D)Sociology":15,
      "(M)Criminology":49,
      "(B)Sociology":140,
    },
  },
  "Faculty of Law":{
    "":{
      "(D)Law":48,
      "(D)Enterprise Juridical Sciences":1,
      "(D)Comparative Juridical Sciences":1,
      "(D)Private Juridical Sciences":2,
      "(D)Public or Political Juridical Sciences":2,
      "(M)Juridical Sciences in Chinese Language":106,
      "(M)Juridical - Political Sciences in Chinese Language":4,
      "(M)International Business Law":87,
      "(M)Master Of Law In English Language":1,
      "(M)Comparative Law":5,
      "(M)European Union Law":14,
      "(M)International Law":36,
      "(M)Juridical Sciences":21,
      "(M)Chinese Language - Constitutional Law, Basic Law and Administrative Law":11,
      "(M)Chinese Language - Comparative Civil Law":19,
      "(M)Chinese Language - International Commercial Law":12,
      "(M)Chinese Language - Comparative Criminal Law":19,
      "(P)Postgraduate Certificate in Law in Chinese Language":9,
      "(P)Postgraduate Programme in International Business Law":2,
      "(P)Introduction to Macau Law":68,
      "(B)Law in Chinese Language":4,
      "(B)Law in Chinese Language":1,
      "(B)Law":150,
      "(B)Law":199,
      "(B)Law":74,
    },
  },
  "Faculty of Health Sciences":{
    "":{
      "(D)Biomedical Sciences":1,
    },
  },
  "Faculty of Science and Technology":{
    "Department of Civil and Environmental Engineering":{
      "(D)Civil Engineering":10,
      "(M)Civil Engineering":75,
      "(B)Civil Engineering":183,
    },
    "Department of Computer and Information Science":{
      "(D)Software Engineering":48,
      "(M)E-Commerce Technology":48,
      "(M)E-Commerce Technology":38,
      "(M)Software Engineering":92,
      "(B)Computer Science":138,
      "(B)Software Engineering":41,
    },
    "Department of Electrical and Computer Engineering":{
      "(D)Electrical and Electronics Engineering":23,
      "(D)Electrical and Computer Engineering":17,
      "(M)Electrical and Electronics Engineering":42,
      "(M)Electrical and Computer Engineering":39,
      "(B)Electrical and Computer Engineering":129,
      "(B)Electrical and Electronics Engineering":34,
    },
    "Department of Electromechanical Engineering":{
      "(D)Electromechanical Engineering":18,
      "(M)Electromechanical Engineering":105,
      "(B)Electromechanical Engineering":181,
    },
    "Department of Mathematics":{
      "(D)Mathematics":19,
      "(M)Mathematics":52,
      "(B)Mathematics":111,
    },
  },
}
