var json = {
             id:0,
             name:"University",
             data:{
               type:"university",
               level:0,
               $area:9088
             },
             children:[
             {
               id:8,
               name:"Institute of Chinese Medical Sciences",
               data:{
                 type:"faculty",
                 level:1,
                 $area:247
               },
               children:[
               {
                 id:58,
                 name:"",
                 data:{
                   type:"department",
                   level:2,
                   $area:247
                 },
                 children:[
                 {
                   id:59,
                   name:"(D)Biomedical Sciences",
                   data:{
                     type:"major",
                     level:3,
                     $area:88
                   },
                   children:[]
                 },
                 {
                   id:108,
                   name:"(M)Chinese Medicinal Science",
                   data:{
                     type:"major",
                     level:3,
                     $area:64
                   },
                   children:[]
                 },
                 {
                   id:109,
                   name:"(M)Medicinal Administration",
                   data:{
                     type:"major",
                     level:3,
                     $area:63
                   },
                   children:[]
                 },
                 {
                   id:169,
                   name:"(B)Biomedical Sciences",
                   data:{
                     type:"major",
                     level:3,
                     $area:32
                   },
                   children:[]
                 },
                 ]
               },
               ]
             },
             {
               id:3,
               name:"Faculty of Education",
               data:{
                 type:"faculty",
                 level:1,
                 $area:533
               },
               children:[
               {
                 id:24,
                 name:"",
                 data:{
                   type:"department",
                   level:2,
                   $area:533
                 },
                 children:[
                 {
                   id:25,
                   name:"(D)Education",
                   data:{
                     type:"major",
                     level:3,
                     $area:14
                   },
                   children:[]
                 },
                 {
                   id:110,
                   name:"(P)Postgraduate Certificate in Education",
                   data:{
                     type:"major",
                     level:3,
                     $area:8
                   },
                   children:[]
                 },
                 {
                   id:111,
                   name:"(P)Postgraduate Certificate in Education",
                   data:{
                     type:"major",
                     level:3,
                     $area:19
                   },
                   children:[]
                 },
                 {
                   id:143,
                   name:"(B)Chinese",
                   data:{
                     type:"major",
                     level:3,
                     $area:121
                   },
                   children:[]
                 },
                 {
                   id:144,
                   name:"(B)English",
                   data:{
                     type:"major",
                     level:3,
                     $area:106
                   },
                   children:[]
                 },
                 {
                   id:145,
                   name:"(B)Mathematics",
                   data:{
                     type:"major",
                     level:3,
                     $area:18
                   },
                   children:[]
                 },
                 {
                   id:146,
                   name:"(B)Pre-Primary Education",
                   data:{
                     type:"major",
                     level:3,
                     $area:117
                   },
                   children:[]
                 },
                 {
                   id:147,
                   name:"(B)Primary Education",
                   data:{
                     type:"major",
                     level:3,
                     $area:130
                   },
                   children:[]
                 },
                 ]
               },
               ]
             },
             {
               id:2,
               name:"Faculty of Business Administration",
               data:{
                 type:"faculty",
                 level:1,
                 $area:2030
               },
               children:[
               {
                 id:19,
                 name:"",
                 data:{
                   type:"department",
                   level:2,
                   $area:343
                 },
                 children:[
                 {
                   id:20,
                   name:"(D)Business Administration",
                   data:{
                     type:"major",
                     level:3,
                     $area:27
                   },
                   children:[]
                 },
                 {
                   id:21,
                   name:"(D)Database Management and Information System",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 {
                   id:22,
                   name:"(D)Economics",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 {
                   id:23,
                   name:"(D)Strategic Management",
                   data:{
                     type:"major",
                     level:3,
                     $area:2
                   },
                   children:[]
                 },
                 {
                   id:124,
                   name:"(B)Business Administration",
                   data:{
                     type:"major",
                     level:3,
                     $area:312
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:125,
                 name:"Department of Accounting and Information Management",
                 data:{
                   type:"department",
                   level:2,
                   $area:444
                 },
                 children:[
                 {
                   id:126,
                   name:"(B)Accounting",
                   data:{
                     type:"major",
                     level:3,
                     $area:381
                   },
                   children:[]
                 },
                 {
                   id:127,
                   name:"(B)Business Information System",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 {
                   id:128,
                   name:"(B)Electronic Business",
                   data:{
                     type:"major",
                     level:3,
                     $area:62
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:129,
                 name:"Department of Finance and Business Economics",
                 data:{
                   type:"department",
                   level:2,
                   $area:432
                 },
                 children:[
                 {
                   id:130,
                   name:"(B)Business Economics",
                   data:{
                     type:"major",
                     level:3,
                     $area:90
                   },
                   children:[]
                 },
                 {
                   id:131,
                   name:"(B)Economics and International Finance",
                   data:{
                     type:"major",
                     level:3,
                     $area:4
                   },
                   children:[]
                 },
                 {
                   id:132,
                   name:"(B)Financial Controllership",
                   data:{
                     type:"major",
                     level:3,
                     $area:63
                   },
                   children:[]
                 },
                 {
                   id:133,
                   name:"(B)Finance",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 {
                   id:134,
                   name:"(B)Finance",
                   data:{
                     type:"major",
                     level:3,
                     $area:274
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:135,
                 name:"Department of Management and Marketing",
                 data:{
                   type:"department",
                   level:2,
                   $area:811
                 },
                 children:[
                 {
                   id:136,
                   name:"(B)Global Business Management",
                   data:{
                     type:"major",
                     level:3,
                     $area:118
                   },
                   children:[]
                 },
                 {
                   id:137,
                   name:"(B)Gaming Management",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 {
                   id:138,
                   name:"(B)Human Resources Management",
                   data:{
                     type:"major",
                     level:3,
                     $area:226
                   },
                   children:[]
                 },
                 {
                   id:139,
                   name:"(B)Management",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 {
                   id:140,
                   name:"(B)Marketing",
                   data:{
                     type:"major",
                     level:3,
                     $area:190
                   },
                   children:[]
                 },
                 {
                   id:141,
                   name:"(B)Gaming and Hospitality Management",
                   data:{
                     type:"major",
                     level:3,
                     $area:66
                   },
                   children:[]
                 },
                 {
                   id:142,
                   name:"(B)Hospitality and Gaming Management",
                   data:{
                     type:"major",
                     level:3,
                     $area:209
                   },
                   children:[]
                 },
                 ]
               },
               ]
             },
             {
               id:1,
               name:"Faculty of Arts and Humanities",
               data:{
                 type:"faculty",
                 level:1,
                 $area:1978
               },
               children:[
               {
                 id:9,
                 name:"Department of Chinese",
                 data:{
                   type:"department",
                   level:2,
                   $area:388
                 },
                 children:[
                 {
                   id:10,
                   name:"(D)Linguistics/Linguistics",
                   data:{
                     type:"major",
                     level:3,
                     $area:16
                   },
                   children:[]
                 },
                 {
                   id:11,
                   name:"(D)Literary Studies/Literary Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:27
                   },
                   children:[]
                 },
                 {
                   id:60,
                   name:"(M)Chinese Studies in Literature Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:4
                   },
                   children:[]
                 },
                 {
                   id:61,
                   name:"(M)Chinese Linguistics",
                   data:{
                     type:"major",
                     level:3,
                     $area:39
                   },
                   children:[]
                 },
                 {
                   id:62,
                   name:"(M)Chinese Literature",
                   data:{
                     type:"major",
                     level:3,
                     $area:69
                   },
                   children:[]
                 },
                 {
                   id:115,
                   name:"(B)Chinese Language and Literature",
                   data:{
                     type:"major",
                     level:3,
                     $area:61
                   },
                   children:[]
                 },
                 {
                   id:116,
                   name:"(B)Chinese Language and Literature",
                   data:{
                     type:"major",
                     level:3,
                     $area:172
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:12,
                 name:"Department of English",
                 data:{
                   type:"department",
                   level:2,
                   $area:473
                 },
                 children:[
                 {
                   id:13,
                   name:"(D)Linguistics/Linguistics",
                   data:{
                     type:"major",
                     level:3,
                     $area:14
                   },
                   children:[]
                 },
                 {
                   id:14,
                   name:"(D)Literary Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:5
                   },
                   children:[]
                 },
                 {
                   id:15,
                   name:"(D)Philosophy and Religious Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:6
                   },
                   children:[]
                 },
                 {
                   id:63,
                   name:"(M)Applied English",
                   data:{
                     type:"major",
                     level:3,
                     $area:5
                   },
                   children:[]
                 },
                 {
                   id:64,
                   name:"(M)English Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:91
                   },
                   children:[]
                 },
                 {
                   id:65,
                   name:"(M)Translation Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:114
                   },
                   children:[]
                 },
                 {
                   id:117,
                   name:"(B)English Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:54
                   },
                   children:[]
                 },
                 {
                   id:118,
                   name:"(B)English Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:184
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:16,
                 name:"Department of Portuguese",
                 data:{
                   type:"department",
                   level:2,
                   $area:325
                 },
                 children:[
                 {
                   id:17,
                   name:"(D)Linguistics/Linguistics",
                   data:{
                     type:"major",
                     level:3,
                     $area:7
                   },
                   children:[]
                 },
                 {
                   id:18,
                   name:"(D)Literary Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:2
                   },
                   children:[]
                 },
                 {
                   id:66,
                   name:"(M)Portuguese Language and Culture",
                   data:{
                     type:"major",
                     level:3,
                     $area:32
                   },
                   children:[]
                 },
                 {
                   id:122,
                   name:"(B)Portuguese Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:70
                   },
                   children:[]
                 },
                 {
                   id:123,
                   name:"(B)Portuguese Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:214
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:67,
                 name:"Faculty of Business Administration",
                 data:{
                   type:"department",
                   level:2,
                   $area:409
                 },
                 children:[
                 {
                   id:68,
                   name:"(M)Business Administration",
                   data:{
                     type:"major",
                     level:3,
                     $area:183
                   },
                   children:[]
                 },
                 {
                   id:69,
                   name:"(M)Accounting",
                   data:{
                     type:"major",
                     level:3,
                     $area:102
                   },
                   children:[]
                 },
                 {
                   id:70,
                   name:"(M)Finance",
                   data:{
                     type:"major",
                     level:3,
                     $area:71
                   },
                   children:[]
                 },
                 {
                   id:71,
                   name:"(M)International Integrated Resort Management",
                   data:{
                     type:"major",
                     level:3,
                     $area:53
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:72,
                 name:"Faculty of Education",
                 data:{
                   type:"department",
                   level:2,
                   $area:203
                 },
                 children:[
                 {
                   id:73,
                   name:"(M)Curriculum and Instruction",
                   data:{
                     type:"major",
                     level:3,
                     $area:65
                   },
                   children:[]
                 },
                 {
                   id:74,
                   name:"(M)Educational Administration",
                   data:{
                     type:"major",
                     level:3,
                     $area:26
                   },
                   children:[]
                 },
                 {
                   id:75,
                   name:"(M)Early Childhood Education and Child Development",
                   data:{
                     type:"major",
                     level:3,
                     $area:12
                   },
                   children:[]
                 },
                 {
                   id:76,
                   name:"(M)Early Childhood Education and Human Development",
                   data:{
                     type:"major",
                     level:3,
                     $area:17
                   },
                   children:[]
                 },
                 {
                   id:77,
                   name:"(M)Educational Psychology",
                   data:{
                     type:"major",
                     level:3,
                     $area:22
                   },
                   children:[]
                 },
                 {
                   id:78,
                   name:"(M)Physical Education and Sport Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:45
                   },
                   children:[]
                 },
                 {
                   id:79,
                   name:"(M)School Counseling",
                   data:{
                     type:"major",
                     level:3,
                     $area:16
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:119,
                 name:"Centre for Japanese Studies",
                 data:{
                   type:"department",
                   level:2,
                   $area:180
                 },
                 children:[
                 {
                   id:120,
                   name:"(B)Japanese Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:137
                   },
                   children:[]
                 },
                 {
                   id:121,
                   name:"(B)Japanese Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:43
                   },
                   children:[]
                 },
                 ]
               },
               ]
             },
             {
               id:7,
               name:"Faculty of Social Sciences",
               data:{
                 type:"faculty",
                 level:1,
                 $area:1960
               },
               children:[
               {
                 id:45,
                 name:"Department of Communication",
                 data:{
                   type:"department",
                   level:2,
                   $area:506
                 },
                 children:[
                 {
                   id:46,
                   name:"(D)Communication",
                   data:{
                     type:"major",
                     level:3,
                     $area:18
                   },
                   children:[]
                 },
                 {
                   id:100,
                   name:"(M)Communication and New Media",
                   data:{
                     type:"major",
                     level:3,
                     $area:79
                   },
                   children:[]
                 },
                 {
                   id:160,
                   name:"(B)English Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:65
                   },
                   children:[]
                 },
                 {
                   id:161,
                   name:"(B)Communication",
                   data:{
                     type:"major",
                     level:3,
                     $area:295
                   },
                   children:[]
                 },
                 {
                   id:162,
                   name:"(B)Journalism and Public Communication",
                   data:{
                     type:"major",
                     level:3,
                     $area:49
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:47,
                 name:"Department of Economics",
                 data:{
                   type:"department",
                   level:2,
                   $area:308
                 },
                 children:[
                 {
                   id:48,
                   name:"(D)Economics",
                   data:{
                     type:"major",
                     level:3,
                     $area:4
                   },
                   children:[]
                 },
                 {
                   id:101,
                   name:"(M)Economics",
                   data:{
                     type:"major",
                     level:3,
                     $area:47
                   },
                   children:[]
                 },
                 {
                   id:163,
                   name:"(B)Economics",
                   data:{
                     type:"major",
                     level:3,
                     $area:257
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:49,
                 name:"Department of Government and Public Administration",
                 data:{
                   type:"department",
                   level:2,
                   $area:589
                 },
                 children:[
                 {
                   id:50,
                   name:"(D)Public Administration",
                   data:{
                     type:"major",
                     level:3,
                     $area:8
                   },
                   children:[]
                 },
                 {
                   id:51,
                   name:"(D)Political Science",
                   data:{
                     type:"major",
                     level:3,
                     $area:10
                   },
                   children:[]
                 },
                 {
                   id:102,
                   name:"(M)International Relations and Public Policy",
                   data:{
                     type:"major",
                     level:3,
                     $area:74
                   },
                   children:[]
                 },
                 {
                   id:103,
                   name:"(M)European Studies",
                   data:{
                     type:"major",
                     level:3,
                     $area:59
                   },
                   children:[]
                 },
                 {
                   id:104,
                   name:"(M)Public Administration",
                   data:{
                     type:"major",
                     level:3,
                     $area:136
                   },
                   children:[]
                 },
                 {
                   id:164,
                   name:"(B)Public Administration",
                   data:{
                     type:"major",
                     level:3,
                     $area:2
                   },
                   children:[]
                 },
                 {
                   id:165,
                   name:"(B)Government and Public Administration",
                   data:{
                     type:"major",
                     level:3,
                     $area:300
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:52,
                 name:"Department of History",
                 data:{
                   type:"department",
                   level:2,
                   $area:172
                 },
                 children:[
                 {
                   id:53,
                   name:"(D)History",
                   data:{
                     type:"major",
                     level:3,
                     $area:14
                   },
                   children:[]
                 },
                 {
                   id:105,
                   name:"(M)History",
                   data:{
                     type:"major",
                     level:3,
                     $area:44
                   },
                   children:[]
                 },
                 {
                   id:166,
                   name:"(B)History",
                   data:{
                     type:"major",
                     level:3,
                     $area:114
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:54,
                 name:"Department of Psychology",
                 data:{
                   type:"department",
                   level:2,
                   $area:181
                 },
                 children:[
                 {
                   id:55,
                   name:"(D)Psychology",
                   data:{
                     type:"major",
                     level:3,
                     $area:11
                   },
                   children:[]
                 },
                 {
                   id:106,
                   name:"(M)Clinical Psychology",
                   data:{
                     type:"major",
                     level:3,
                     $area:15
                   },
                   children:[]
                 },
                 {
                   id:167,
                   name:"(B)Psychology",
                   data:{
                     type:"major",
                     level:3,
                     $area:155
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:56,
                 name:"Department of Sociology",
                 data:{
                   type:"department",
                   level:2,
                   $area:204
                 },
                 children:[
                 {
                   id:57,
                   name:"(D)Sociology",
                   data:{
                     type:"major",
                     level:3,
                     $area:15
                   },
                   children:[]
                 },
                 {
                   id:107,
                   name:"(M)Criminology",
                   data:{
                     type:"major",
                     level:3,
                     $area:49
                   },
                   children:[]
                 },
                 {
                   id:168,
                   name:"(B)Sociology",
                   data:{
                     type:"major",
                     level:3,
                     $area:140
                   },
                   children:[]
                 },
                 ]
               },
               ]
             },
             {
               id:5,
               name:"Faculty of Law",
               data:{
                 type:"faculty",
                 level:1,
                 $area:896
               },
               children:[
               {
                 id:28,
                 name:"",
                 data:{
                   type:"department",
                   level:2,
                   $area:896
                 },
                 children:[
                 {
                   id:29,
                   name:"(D)Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:48
                   },
                   children:[]
                 },
                 {
                   id:30,
                   name:"(D)Enterprise Juridical Sciences",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 {
                   id:31,
                   name:"(D)Comparative Juridical Sciences",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 {
                   id:32,
                   name:"(D)Private Juridical Sciences",
                   data:{
                     type:"major",
                     level:3,
                     $area:2
                   },
                   children:[]
                 },
                 {
                   id:33,
                   name:"(D)Public or Political Juridical Sciences",
                   data:{
                     type:"major",
                     level:3,
                     $area:2
                   },
                   children:[]
                 },
                 {
                   id:80,
                   name:"(M)Juridical Sciences in Chinese Language",
                   data:{
                     type:"major",
                     level:3,
                     $area:106
                   },
                   children:[]
                 },
                 {
                   id:81,
                   name:"(M)Juridical - Political Sciences in Chinese Language",
                   data:{
                     type:"major",
                     level:3,
                     $area:4
                   },
                   children:[]
                 },
                 {
                   id:82,
                   name:"(M)International Business Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:87
                   },
                   children:[]
                 },
                 {
                   id:83,
                   name:"(M)Master Of Law In English Language",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 {
                   id:84,
                   name:"(M)Comparative Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:5
                   },
                   children:[]
                 },
                 {
                   id:85,
                   name:"(M)European Union Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:14
                   },
                   children:[]
                 },
                 {
                   id:86,
                   name:"(M)International Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:36
                   },
                   children:[]
                 },
                 {
                   id:87,
                   name:"(M)Juridical Sciences",
                   data:{
                     type:"major",
                     level:3,
                     $area:21
                   },
                   children:[]
                 },
                 {
                   id:88,
                   name:"(M)Chinese Language - Constitutional Law, Basic Law and Administrative Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:11
                   },
                   children:[]
                 },
                 {
                   id:89,
                   name:"(M)Chinese Language - Comparative Civil Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:19
                   },
                   children:[]
                 },
                 {
                   id:90,
                   name:"(M)Chinese Language - International Commercial Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:12
                   },
                   children:[]
                 },
                 {
                   id:91,
                   name:"(M)Chinese Language - Comparative Criminal Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:19
                   },
                   children:[]
                 },
                 {
                   id:112,
                   name:"(P)Postgraduate Certificate in Law in Chinese Language",
                   data:{
                     type:"major",
                     level:3,
                     $area:9
                   },
                   children:[]
                 },
                 {
                   id:113,
                   name:"(P)Postgraduate Programme in International Business Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:2
                   },
                   children:[]
                 },
                 {
                   id:114,
                   name:"(P)Introduction to Macau Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:68
                   },
                   children:[]
                 },
                 {
                   id:148,
                   name:"(B)Law in Chinese Language",
                   data:{
                     type:"major",
                     level:3,
                     $area:4
                   },
                   children:[]
                 },
                 {
                   id:149,
                   name:"(B)Law in Chinese Language",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 {
                   id:150,
                   name:"(B)Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:150
                   },
                   children:[]
                 },
                 {
                   id:151,
                   name:"(B)Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:199
                   },
                   children:[]
                 },
                 {
                   id:152,
                   name:"(B)Law",
                   data:{
                     type:"major",
                     level:3,
                     $area:74
                   },
                   children:[]
                 },
                 ]
               },
               ]
             },
             {
               id:4,
               name:"Faculty of Health Sciences",
               data:{
                 type:"faculty",
                 level:1,
                 $area:1
               },
               children:[
               {
                 id:26,
                 name:"",
                 data:{
                   type:"department",
                   level:2,
                   $area:1
                 },
                 children:[
                 {
                   id:27,
                   name:"(D)Biomedical Sciences",
                   data:{
                     type:"major",
                     level:3,
                     $area:1
                   },
                   children:[]
                 },
                 ]
               },
               ]
             },
             {
               id:6,
               name:"Faculty of Science and Technology",
               data:{
                 type:"faculty",
                 level:1,
                 $area:1443
               },
               children:[
               {
                 id:34,
                 name:"Department of Civil and Environmental Engineering",
                 data:{
                   type:"department",
                   level:2,
                   $area:268
                 },
                 children:[
                 {
                   id:35,
                   name:"(D)Civil Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:10
                   },
                   children:[]
                 },
                 {
                   id:92,
                   name:"(M)Civil Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:75
                   },
                   children:[]
                 },
                 {
                   id:153,
                   name:"(B)Civil Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:183
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:36,
                 name:"Department of Computer and Information Science",
                 data:{
                   type:"department",
                   level:2,
                   $area:405
                 },
                 children:[
                 {
                   id:37,
                   name:"(D)Software Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:48
                   },
                   children:[]
                 },
                 {
                   id:93,
                   name:"(M)E-Commerce Technology",
                   data:{
                     type:"major",
                     level:3,
                     $area:48
                   },
                   children:[]
                 },
                 {
                   id:94,
                   name:"(M)E-Commerce Technology",
                   data:{
                     type:"major",
                     level:3,
                     $area:38
                   },
                   children:[]
                 },
                 {
                   id:95,
                   name:"(M)Software Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:92
                   },
                   children:[]
                 },
                 {
                   id:157,
                   name:"(B)Computer Science",
                   data:{
                     type:"major",
                     level:3,
                     $area:138
                   },
                   children:[]
                 },
                 {
                   id:158,
                   name:"(B)Software Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:41
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:38,
                 name:"Department of Electrical and Computer Engineering",
                 data:{
                   type:"department",
                   level:2,
                   $area:284
                 },
                 children:[
                 {
                   id:39,
                   name:"(D)Electrical and Electronics Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:23
                   },
                   children:[]
                 },
                 {
                   id:40,
                   name:"(D)Electrical and Computer Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:17
                   },
                   children:[]
                 },
                 {
                   id:96,
                   name:"(M)Electrical and Electronics Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:42
                   },
                   children:[]
                 },
                 {
                   id:97,
                   name:"(M)Electrical and Computer Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:39
                   },
                   children:[]
                 },
                 {
                   id:154,
                   name:"(B)Electrical and Computer Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:129
                   },
                   children:[]
                 },
                 {
                   id:155,
                   name:"(B)Electrical and Electronics Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:34
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:41,
                 name:"Department of Electromechanical Engineering",
                 data:{
                   type:"department",
                   level:2,
                   $area:304
                 },
                 children:[
                 {
                   id:42,
                   name:"(D)Electromechanical Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:18
                   },
                   children:[]
                 },
                 {
                   id:98,
                   name:"(M)Electromechanical Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:105
                   },
                   children:[]
                 },
                 {
                   id:156,
                   name:"(B)Electromechanical Engineering",
                   data:{
                     type:"major",
                     level:3,
                     $area:181
                   },
                   children:[]
                 },
                 ]
               },
               {
                 id:43,
                 name:"Department of Mathematics",
                 data:{
                   type:"department",
                   level:2,
                   $area:182
                 },
                 children:[
                 {
                   id:44,
                   name:"(D)Mathematics",
                   data:{
                     type:"major",
                     level:3,
                     $area:19
                   },
                   children:[]
                 },
                 {
                   id:99,
                   name:"(M)Mathematics",
                   data:{
                     type:"major",
                     level:3,
                     $area:52
                   },
                   children:[]
                 },
                 {
                   id:159,
                   name:"(B)Mathematics",
                   data:{
                     type:"major",
                     level:3,
                     $area:111
                   },
                   children:[]
                 },
                 ]
               },
               ]
             },
             ]
           }