var json = {
  id:0,
  name:"null",
  data:{
    type:"null",
    level:0,
    $area:9088
  },
  children:[
  {
    id:8,
    name:"Institute of Chinese Medical Sciences",
    data:{
      type:"faculty",
      level:1,
      $area:247
    },
    children:[
    {
      id:58,
      name:"",
      data:{
        type:"department",
        level:2,
        $area:247
      },
      children:[
      {
        id:59,
        name:"Doctoral - Biomedical Sciences (PBS06 / DBS)",
        data:{
          type:"major",
          level:3,
          $area:88
        },
        children:[]
      },
      {
        id:108,
        name:"Master - Chinese Medicinal Science (MCM-CMS)",
        data:{
          type:"major",
          level:3,
          $area:64
        },
        children:[]
      },
      {
        id:109,
        name:"Master - Medicinal Administration (MCM-MAD)",
        data:{
          type:"major",
          level:3,
          $area:63
        },
        children:[]
      },
      {
        id:169,
        name:"Bachelor - Biomedical Sciences (BIO11)",
        data:{
          type:"major",
          level:3,
          $area:32
        },
        children:[]
      },
      ]
    },
    ]
  },
  {
    id:3,
    name:"Faculty of Education",
    data:{
      type:"faculty",
      level:1,
      $area:533
    },
    children:[
    {
      id:24,
      name:"",
      data:{
        type:"department",
        level:2,
        $area:533
      },
      children:[
      {
        id:25,
        name:"Doctoral - Education (PED06 / DED)",
        data:{
          type:"major",
          level:3,
          $area:14
        },
        children:[]
      },
      {
        id:110,
        name:"Postgraduate Certificate/Diploma - Postgraduate Certificate in Education (Day-Time) (PED)",
        data:{
          type:"major",
          level:3,
          $area:8
        },
        children:[]
      },
      {
        id:111,
        name:"Postgraduate Certificate/Diploma - Postgraduate Certificate in Education (Evening) (PEE)",
        data:{
          type:"major",
          level:3,
          $area:19
        },
        children:[]
      },
      {
        id:143,
        name:"Bachelor - Chinese (CHN / CHN11)",
        data:{
          type:"major",
          level:3,
          $area:121
        },
        children:[]
      },
      {
        id:144,
        name:"Bachelor - English (EN / ENN / ENG11)",
        data:{
          type:"major",
          level:3,
          $area:106
        },
        children:[]
      },
      {
        id:145,
        name:"Bachelor - Mathematics (MMS)",
        data:{
          type:"major",
          level:3,
          $area:18
        },
        children:[]
      },
      {
        id:146,
        name:"Bachelor - Pre-Primary Education (PPY / PPE11)",
        data:{
          type:"major",
          level:3,
          $area:117
        },
        children:[]
      },
      {
        id:147,
        name:"Bachelor - Primary Education (PRY / PYE11)",
        data:{
          type:"major",
          level:3,
          $area:130
        },
        children:[]
      },
      ]
    },
    ]
  },
  {
    id:2,
    name:"Faculty of Business Administration",
    data:{
      type:"faculty",
      level:1,
      $area:2030
    },
    children:[
    {
      id:19,
      name:"",
      data:{
        type:"department",
        level:2,
        $area:343
      },
      children:[
      {
        id:20,
        name:"Doctoral - Business Administration (DBA)",
        data:{
          type:"major",
          level:3,
          $area:27
        },
        children:[]
      },
      {
        id:21,
        name:"Doctoral - Database Management and Information System (PDM06)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      {
        id:22,
        name:"Doctoral - Economics (PEC06)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      {
        id:23,
        name:"Doctoral - Strategic Management (PSM06)",
        data:{
          type:"major",
          level:3,
          $area:2
        },
        children:[]
      },
      {
        id:124,
        name:"Bachelor - Business Administration (BBA / GBS11)",
        data:{
          type:"major",
          level:3,
          $area:312
        },
        children:[]
      },
      ]
    },
    {
      id:125,
      name:"Department of Accounting and Information Management",
      data:{
        type:"department",
        level:2,
        $area:444
      },
      children:[
      {
        id:126,
        name:"Bachelor - Accounting (BSc-ACC / ACC11 / ACC13)",
        data:{
          type:"major",
          level:3,
          $area:381
        },
        children:[]
      },
      {
        id:127,
        name:"Bachelor - Business Information System (BIS)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      {
        id:128,
        name:"Bachelor - Electronic Business (ELB / ELB11)",
        data:{
          type:"major",
          level:3,
          $area:62
        },
        children:[]
      },
      ]
    },
    {
      id:129,
      name:"Department of Finance and Business Economics",
      data:{
        type:"department",
        level:2,
        $area:432
      },
      children:[
      {
        id:130,
        name:"Bachelor - Business Economics (BEC / BEC11)",
        data:{
          type:"major",
          level:3,
          $area:90
        },
        children:[]
      },
      {
        id:131,
        name:"Bachelor - Economics and International Finance (EIF)",
        data:{
          type:"major",
          level:3,
          $area:4
        },
        children:[]
      },
      {
        id:132,
        name:"Bachelor - Financial Controllership (FIC / FIC11)",
        data:{
          type:"major",
          level:3,
          $area:63
        },
        children:[]
      },
      {
        id:133,
        name:"Bachelor - Finance (FNC)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      {
        id:134,
        name:"Bachelor - Finance (BSc-FNS / FNC11)",
        data:{
          type:"major",
          level:3,
          $area:274
        },
        children:[]
      },
      ]
    },
    {
      id:135,
      name:"Department of Management and Marketing",
      data:{
        type:"department",
        level:2,
        $area:811
      },
      children:[
      {
        id:136,
        name:"Bachelor - Global Business Management (GBM / GBM11)",
        data:{
          type:"major",
          level:3,
          $area:118
        },
        children:[]
      },
      {
        id:137,
        name:"Bachelor - Gaming Management (GM)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      {
        id:138,
        name:"Bachelor - Human Resources Management (HRM / HRM11)",
        data:{
          type:"major",
          level:3,
          $area:226
        },
        children:[]
      },
      {
        id:139,
        name:"Bachelor - Management (MGM)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      {
        id:140,
        name:"Bachelor - Marketing (MKK / MTG / MKG11)",
        data:{
          type:"major",
          level:3,
          $area:190
        },
        children:[]
      },
      {
        id:141,
        name:"Bachelor - Gaming and Hospitality Management (BSc-GHM)",
        data:{
          type:"major",
          level:3,
          $area:66
        },
        children:[]
      },
      {
        id:142,
        name:"Bachelor - Hospitality and Gaming Management (BSc-HGM11)",
        data:{
          type:"major",
          level:3,
          $area:209
        },
        children:[]
      },
      ]
    },
    ]
  },
  {
    id:1,
    name:"Faculty of Arts and Humanities",
    data:{
      type:"faculty",
      level:1,
      $area:1978
    },
    children:[
    {
      id:9,
      name:"Department of Chinese",
      data:{
        type:"department",
        level:2,
        $area:388
      },
      children:[
      {
        id:10,
        name:"Doctoral - Linguistics/Linguistics (Chinese) (PLN06 / DLC)",
        data:{
          type:"major",
          level:3,
          $area:16
        },
        children:[]
      },
      {
        id:11,
        name:"Doctoral - Literary Studies/Literary Studies (Chinese) (PLS06 / DSC)",
        data:{
          type:"major",
          level:3,
          $area:27
        },
        children:[]
      },
      {
        id:60,
        name:"Master - Chinese Studies in Literature Studies (MCS-LT)",
        data:{
          type:"major",
          level:3,
          $area:4
        },
        children:[]
      },
      {
        id:61,
        name:"Master - Chinese Linguistics (MAH-CLN)",
        data:{
          type:"major",
          level:3,
          $area:39
        },
        children:[]
      },
      {
        id:62,
        name:"Master - Chinese Literature (MAH-CLT)",
        data:{
          type:"major",
          level:3,
          $area:69
        },
        children:[]
      },
      {
        id:115,
        name:"Bachelor - Chinese Language and Literature (CCH)",
        data:{
          type:"major",
          level:3,
          $area:61
        },
        children:[]
      },
      {
        id:116,
        name:"Bachelor - Chinese Language and Literature (CLL11)",
        data:{
          type:"major",
          level:3,
          $area:172
        },
        children:[]
      },
      ]
    },
    {
      id:12,
      name:"Department of English",
      data:{
        type:"department",
        level:2,
        $area:473
      },
      children:[
      {
        id:13,
        name:"Doctoral - Linguistics/Linguistics (English) (PLN06 / DLE)",
        data:{
          type:"major",
          level:3,
          $area:14
        },
        children:[]
      },
      {
        id:14,
        name:"Doctoral - Literary Studies (English) (DSE)",
        data:{
          type:"major",
          level:3,
          $area:5
        },
        children:[]
      },
      {
        id:15,
        name:"Doctoral - Philosophy and Religious Studies (DRS)",
        data:{
          type:"major",
          level:3,
          $area:6
        },
        children:[]
      },
      {
        id:63,
        name:"Master - Applied English (MAH-APP)",
        data:{
          type:"major",
          level:3,
          $area:5
        },
        children:[]
      },
      {
        id:64,
        name:"Master - English Studies (MAH-ELS / ENG)",
        data:{
          type:"major",
          level:3,
          $area:91
        },
        children:[]
      },
      {
        id:65,
        name:"Master - Translation Studies (MAH-TRS)",
        data:{
          type:"major",
          level:3,
          $area:114
        },
        children:[]
      },
      {
        id:117,
        name:"Bachelor - English Studies (ELL)",
        data:{
          type:"major",
          level:3,
          $area:54
        },
        children:[]
      },
      {
        id:118,
        name:"Bachelor - English Studies (ENS11)",
        data:{
          type:"major",
          level:3,
          $area:184
        },
        children:[]
      },
      ]
    },
    {
      id:16,
      name:"Department of Portuguese",
      data:{
        type:"department",
        level:2,
        $area:325
      },
      children:[
      {
        id:17,
        name:"Doctoral - Linguistics/Linguistics (Portuguese) (PLN06 / DLP)",
        data:{
          type:"major",
          level:3,
          $area:7
        },
        children:[]
      },
      {
        id:18,
        name:"Doctoral - Literary Studies (Portuguese) (DSP)",
        data:{
          type:"major",
          level:3,
          $area:2
        },
        children:[]
      },
      {
        id:66,
        name:"Master - Portuguese Language and Culture (MAH-MPL)",
        data:{
          type:"major",
          level:3,
          $area:32
        },
        children:[]
      },
      {
        id:122,
        name:"Bachelor - Portuguese Studies (PTS)",
        data:{
          type:"major",
          level:3,
          $area:70
        },
        children:[]
      },
      {
        id:123,
        name:"Bachelor - Portuguese Studies (PTS11)",
        data:{
          type:"major",
          level:3,
          $area:214
        },
        children:[]
      },
      ]
    },
    {
      id:67,
      name:"Faculty of Business Administration",
      data:{
        type:"department",
        level:2,
        $area:409
      },
      children:[
      {
        id:68,
        name:"Master - Business Administration (MBC)",
        data:{
          type:"major",
          level:3,
          $area:183
        },
        children:[]
      },
      {
        id:69,
        name:"Master - Accounting (MSB-ACN / ACT)",
        data:{
          type:"major",
          level:3,
          $area:102
        },
        children:[]
      },
      {
        id:70,
        name:"Master - Finance (MSB-FAN)",
        data:{
          type:"major",
          level:3,
          $area:71
        },
        children:[]
      },
      {
        id:71,
        name:"Master - International Integrated Resort Management (MSB-IRT)",
        data:{
          type:"major",
          level:3,
          $area:53
        },
        children:[]
      },
      ]
    },
    {
      id:72,
      name:"Faculty of Education",
      data:{
        type:"department",
        level:2,
        $area:203
      },
      children:[
      {
        id:73,
        name:"Master - Curriculum and Instruction (MED-CCI / CIN)",
        data:{
          type:"major",
          level:3,
          $area:65
        },
        children:[]
      },
      {
        id:74,
        name:"Master - Educational Administration (MED-EA)",
        data:{
          type:"major",
          level:3,
          $area:26
        },
        children:[]
      },
      {
        id:75,
        name:"Master - Early Childhood Education and Child Development (ECD)",
        data:{
          type:"major",
          level:3,
          $area:12
        },
        children:[]
      },
      {
        id:76,
        name:"Master - Early Childhood Education and Human Development (MED-ECN / ECH)",
        data:{
          type:"major",
          level:3,
          $area:17
        },
        children:[]
      },
      {
        id:77,
        name:"Master - Educational Psychology (MED-EY / EPY)",
        data:{
          type:"major",
          level:3,
          $area:22
        },
        children:[]
      },
      {
        id:78,
        name:"Master - Physical Education and Sport Studies (MED-PES / PSS)",
        data:{
          type:"major",
          level:3,
          $area:45
        },
        children:[]
      },
      {
        id:79,
        name:"Master - School Counseling (MED-SCS)",
        data:{
          type:"major",
          level:3,
          $area:16
        },
        children:[]
      },
      ]
    },
    {
      id:119,
      name:"Centre for Japanese Studies",
      data:{
        type:"department",
        level:2,
        $area:180
      },
      children:[
      {
        id:120,
        name:"Bachelor - Japanese Studies (JAP11)",
        data:{
          type:"major",
          level:3,
          $area:137
        },
        children:[]
      },
      {
        id:121,
        name:"Bachelor - Japanese Studies (JN)",
        data:{
          type:"major",
          level:3,
          $area:43
        },
        children:[]
      },
      ]
    },
    ]
  },
  {
    id:7,
    name:"Faculty of Social Sciences",
    data:{
      type:"faculty",
      level:1,
      $area:1960
    },
    children:[
    {
      id:45,
      name:"Department of Communication",
      data:{
        type:"department",
        level:2,
        $area:506
      },
      children:[
      {
        id:46,
        name:"Doctoral - Communication (PCC / DCC)",
        data:{
          type:"major",
          level:3,
          $area:18
        },
        children:[]
      },
      {
        id:100,
        name:"Master - Communication and New Media (MASS-CNM)",
        data:{
          type:"major",
          level:3,
          $area:79
        },
        children:[]
      },
      {
        id:160,
        name:"Bachelor - English Studies (Communications) (COM)",
        data:{
          type:"major",
          level:3,
          $area:65
        },
        children:[]
      },
      {
        id:161,
        name:"Bachelor - Communication (COM11)",
        data:{
          type:"major",
          level:3,
          $area:295
        },
        children:[]
      },
      {
        id:162,
        name:"Bachelor - Journalism and Public Communication (JPC)",
        data:{
          type:"major",
          level:3,
          $area:49
        },
        children:[]
      },
      ]
    },
    {
      id:47,
      name:"Department of Economics",
      data:{
        type:"department",
        level:2,
        $area:308
      },
      children:[
      {
        id:48,
        name:"Doctoral - Economics (PPE06 / DEC)",
        data:{
          type:"major",
          level:3,
          $area:4
        },
        children:[]
      },
      {
        id:101,
        name:"Master - Economics (MSS-ECO)",
        data:{
          type:"major",
          level:3,
          $area:47
        },
        children:[]
      },
      {
        id:163,
        name:"Bachelor - Economics (EC / ECN11)",
        data:{
          type:"major",
          level:3,
          $area:257
        },
        children:[]
      },
      ]
    },
    {
      id:49,
      name:"Department of Government and Public Administration",
      data:{
        type:"department",
        level:2,
        $area:589
      },
      children:[
      {
        id:50,
        name:"Doctoral - Public Administration (PPA / PPA06 / DPA)",
        data:{
          type:"major",
          level:3,
          $area:8
        },
        children:[]
      },
      {
        id:51,
        name:"Doctoral - Political Science (DPS)",
        data:{
          type:"major",
          level:3,
          $area:10
        },
        children:[]
      },
      {
        id:102,
        name:"Master - International Relations and Public Policy (MASS-IRP)",
        data:{
          type:"major",
          level:3,
          $area:74
        },
        children:[]
      },
      {
        id:103,
        name:"Master - European Studies (MASS-EUS / MES)",
        data:{
          type:"major",
          level:3,
          $area:59
        },
        children:[]
      },
      {
        id:104,
        name:"Master - Public Administration (MPC)",
        data:{
          type:"major",
          level:3,
          $area:136
        },
        children:[]
      },
      {
        id:164,
        name:"Bachelor - Public Administration (Day-Time) (PAM)",
        data:{
          type:"major",
          level:3,
          $area:2
        },
        children:[]
      },
      {
        id:165,
        name:"Bachelor - Government and Public Administration (GPA / GPA11)",
        data:{
          type:"major",
          level:3,
          $area:300
        },
        children:[]
      },
      ]
    },
    {
      id:52,
      name:"Department of History",
      data:{
        type:"department",
        level:2,
        $area:172
      },
      children:[
      {
        id:53,
        name:"Doctoral - History (DHT)",
        data:{
          type:"major",
          level:3,
          $area:14
        },
        children:[]
      },
      {
        id:105,
        name:"Master - History (MASS-HIT)",
        data:{
          type:"major",
          level:3,
          $area:44
        },
        children:[]
      },
      {
        id:166,
        name:"Bachelor - History (HST / HST11)",
        data:{
          type:"major",
          level:3,
          $area:114
        },
        children:[]
      },
      ]
    },
    {
      id:54,
      name:"Department of Psychology",
      data:{
        type:"department",
        level:2,
        $area:181
      },
      children:[
      {
        id:55,
        name:"Doctoral - Psychology (DPC)",
        data:{
          type:"major",
          level:3,
          $area:11
        },
        children:[]
      },
      {
        id:106,
        name:"Master - Clinical Psychology (MSS-CPY)",
        data:{
          type:"major",
          level:3,
          $area:15
        },
        children:[]
      },
      {
        id:167,
        name:"Bachelor - Psychology (PSY / PSY11)",
        data:{
          type:"major",
          level:3,
          $area:155
        },
        children:[]
      },
      ]
    },
    {
      id:56,
      name:"Department of Sociology",
      data:{
        type:"department",
        level:2,
        $area:204
      },
      children:[
      {
        id:57,
        name:"Doctoral - Sociology (PSC / DSY)",
        data:{
          type:"major",
          level:3,
          $area:15
        },
        children:[]
      },
      {
        id:107,
        name:"Master - Criminology (MSS-CR)",
        data:{
          type:"major",
          level:3,
          $area:49
        },
        children:[]
      },
      {
        id:168,
        name:"Bachelor - Sociology (SOC / SOC11)",
        data:{
          type:"major",
          level:3,
          $area:140
        },
        children:[]
      },
      ]
    },
    ]
  },
  {
    id:5,
    name:"Faculty of Law",
    data:{
      type:"faculty",
      level:1,
      $area:896
    },
    children:[
    {
      id:28,
      name:"",
      data:{
        type:"department",
        level:2,
        $area:896
      },
      children:[
      {
        id:29,
        name:"Doctoral - Law (DLL)",
        data:{
          type:"major",
          level:3,
          $area:48
        },
        children:[]
      },
      {
        id:30,
        name:"Doctoral - Enterprise Juridical Sciences (PEJ06)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      {
        id:31,
        name:"Doctoral - Comparative Juridical Sciences (PJC06)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      {
        id:32,
        name:"Doctoral - Private Juridical Sciences (PPJ06)",
        data:{
          type:"major",
          level:3,
          $area:2
        },
        children:[]
      },
      {
        id:33,
        name:"Doctoral - Public or Political Juridical Sciences (PSJ06)",
        data:{
          type:"major",
          level:3,
          $area:2
        },
        children:[]
      },
      {
        id:80,
        name:"Master - Juridical Sciences in Chinese Language (MCL-JC / JDS)",
        data:{
          type:"major",
          level:3,
          $area:106
        },
        children:[]
      },
      {
        id:81,
        name:"Master - Juridical - Political Sciences in Chinese Language (MCL-PC)",
        data:{
          type:"major",
          level:3,
          $area:4
        },
        children:[]
      },
      {
        id:82,
        name:"Master - International Business Law (MIB)",
        data:{
          type:"major",
          level:3,
          $area:87
        },
        children:[]
      },
      {
        id:83,
        name:"Master - Master Of Law In English Language (MLE)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      {
        id:84,
        name:"Master - Comparative Law (MLE-COL)",
        data:{
          type:"major",
          level:3,
          $area:5
        },
        children:[]
      },
      {
        id:85,
        name:"Master - European Union Law (MLE-EUL)",
        data:{
          type:"major",
          level:3,
          $area:14
        },
        children:[]
      },
      {
        id:86,
        name:"Master - International Law (MLE-INL)",
        data:{
          type:"major",
          level:3,
          $area:36
        },
        children:[]
      },
      {
        id:87,
        name:"Master - Juridical Sciences (MLL-JU)",
        data:{
          type:"major",
          level:3,
          $area:21
        },
        children:[]
      },
      {
        id:88,
        name:"Master - Chinese Language - Constitutional Law, Basic Law and Administrative Law (MSL-CBA)",
        data:{
          type:"major",
          level:3,
          $area:11
        },
        children:[]
      },
      {
        id:89,
        name:"Master - Chinese Language - Comparative Civil Law (MSL-CIL)",
        data:{
          type:"major",
          level:3,
          $area:19
        },
        children:[]
      },
      {
        id:90,
        name:"Master - Chinese Language - International Commercial Law (MSL-CML)",
        data:{
          type:"major",
          level:3,
          $area:12
        },
        children:[]
      },
      {
        id:91,
        name:"Master - Chinese Language - Comparative Criminal Law (MSL-CRL)",
        data:{
          type:"major",
          level:3,
          $area:19
        },
        children:[]
      },
      {
        id:112,
        name:"Postgraduate Certificate/Diploma - Postgraduate Certificate in Law in Chinese Language (LCL)",
        data:{
          type:"major",
          level:3,
          $area:9
        },
        children:[]
      },
      {
        id:113,
        name:"Postgraduate Certificate/Diploma - Postgraduate Programme in International Business Law (LIB)",
        data:{
          type:"major",
          level:3,
          $area:2
        },
        children:[]
      },
      {
        id:114,
        name:"Postgraduate Certificate/Diploma - Introduction to Macau Law (Two-Year) (LML)",
        data:{
          type:"major",
          level:3,
          $area:68
        },
        children:[]
      },
      {
        id:148,
        name:"Bachelor - Law in Chinese Language (Evening) (CL)",
        data:{
          type:"major",
          level:3,
          $area:4
        },
        children:[]
      },
      {
        id:149,
        name:"Bachelor - Law in Chinese Language (Day-Time) (CLD)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      {
        id:150,
        name:"Bachelor - Law (Evening) (BL / BLE11)",
        data:{
          type:"major",
          level:3,
          $area:150
        },
        children:[]
      },
      {
        id:151,
        name:"Bachelor - Law (Day-Time) (BLD / BLD13)",
        data:{
          type:"major",
          level:3,
          $area:199
        },
        children:[]
      },
      {
        id:152,
        name:"Bachelor - Law (WA)",
        data:{
          type:"major",
          level:3,
          $area:74
        },
        children:[]
      },
      ]
    },
    ]
  },
  {
    id:4,
    name:"Faculty of Health Sciences",
    data:{
      type:"faculty",
      level:1,
      $area:1
    },
    children:[
    {
      id:26,
      name:"",
      data:{
        type:"department",
        level:2,
        $area:1
      },
      children:[
      {
        id:27,
        name:"Doctoral - Biomedical Sciences (DBM)",
        data:{
          type:"major",
          level:3,
          $area:1
        },
        children:[]
      },
      ]
    },
    ]
  },
  {
    id:6,
    name:"Faculty of Science and Technology",
    data:{
      type:"faculty",
      level:1,
      $area:1443
    },
    children:[
    {
      id:34,
      name:"Department of Civil and Environmental Engineering",
      data:{
        type:"department",
        level:2,
        $area:268
      },
      children:[
      {
        id:35,
        name:"Doctoral - Civil Engineering (DCE)",
        data:{
          type:"major",
          level:3,
          $area:10
        },
        children:[]
      },
      {
        id:92,
        name:"Master - Civil Engineering (MSC-CV / CVL)",
        data:{
          type:"major",
          level:3,
          $area:75
        },
        children:[]
      },
      {
        id:153,
        name:"Bachelor - Civil Engineering (CE / CVE11)",
        data:{
          type:"major",
          level:3,
          $area:183
        },
        children:[]
      },
      ]
    },
    {
      id:36,
      name:"Department of Computer and Information Science",
      data:{
        type:"department",
        level:2,
        $area:405
      },
      children:[
      {
        id:37,
        name:"Doctoral - Software Engineering (PSO06 / DSO)",
        data:{
          type:"major",
          level:3,
          $area:48
        },
        children:[]
      },
      {
        id:93,
        name:"Master - E-Commerce Technology (MSC-ECM)",
        data:{
          type:"major",
          level:3,
          $area:48
        },
        children:[]
      },
      {
        id:94,
        name:"Master - E-Commerce Technology (MSC-EMM)",
        data:{
          type:"major",
          level:3,
          $area:38
        },
        children:[]
      },
      {
        id:95,
        name:"Master - Software Engineering (MSC-SO / SOE)",
        data:{
          type:"major",
          level:3,
          $area:92
        },
        children:[]
      },
      {
        id:157,
        name:"Bachelor - Computer Science (CPS11 / CPS13)",
        data:{
          type:"major",
          level:3,
          $area:138
        },
        children:[]
      },
      {
        id:158,
        name:"Bachelor - Software Engineering (SO)",
        data:{
          type:"major",
          level:3,
          $area:41
        },
        children:[]
      },
      ]
    },
    {
      id:38,
      name:"Department of Electrical and Computer Engineering",
      data:{
        type:"department",
        level:2,
        $area:284
      },
      children:[
      {
        id:39,
        name:"Doctoral - Electrical and Electronics Engineering (PEE06 / DEE)",
        data:{
          type:"major",
          level:3,
          $area:23
        },
        children:[]
      },
      {
        id:40,
        name:"Doctoral - Electrical and Computer Engineering (DET)",
        data:{
          type:"major",
          level:3,
          $area:17
        },
        children:[]
      },
      {
        id:96,
        name:"Master - Electrical and Electronics Engineering (MSC-EE)",
        data:{
          type:"major",
          level:3,
          $area:42
        },
        children:[]
      },
      {
        id:97,
        name:"Master - Electrical and Computer Engineering (MSC-ECT)",
        data:{
          type:"major",
          level:3,
          $area:39
        },
        children:[]
      },
      {
        id:154,
        name:"Bachelor - Electrical and Computer Engineering (ECE11)",
        data:{
          type:"major",
          level:3,
          $area:129
        },
        children:[]
      },
      {
        id:155,
        name:"Bachelor - Electrical and Electronics Engineering (EE)",
        data:{
          type:"major",
          level:3,
          $area:34
        },
        children:[]
      },
      ]
    },
    {
      id:41,
      name:"Department of Electromechanical Engineering",
      data:{
        type:"department",
        level:2,
        $area:304
      },
      children:[
      {
        id:42,
        name:"Doctoral - Electromechanical Engineering (PEM06 / DEM)",
        data:{
          type:"major",
          level:3,
          $area:18
        },
        children:[]
      },
      {
        id:98,
        name:"Master - Electromechanical Engineering (MSC-EM / EMG)",
        data:{
          type:"major",
          level:3,
          $area:105
        },
        children:[]
      },
      {
        id:156,
        name:"Bachelor - Electromechanical Engineering (EL/ EME11)",
        data:{
          type:"major",
          level:3,
          $area:181
        },
        children:[]
      },
      ]
    },
    {
      id:43,
      name:"Department of Mathematics",
      data:{
        type:"department",
        level:2,
        $area:182
      },
      children:[
      {
        id:44,
        name:"Doctoral - Mathematics (DMT)",
        data:{
          type:"major",
          level:3,
          $area:19
        },
        children:[]
      },
      {
        id:99,
        name:"Master - Mathematics (MST-MAT)",
        data:{
          type:"major",
          level:3,
          $area:52
        },
        children:[]
      },
      {
        id:159,
        name:"Bachelor - Mathematics (MTH11)",
        data:{
          type:"major",
          level:3,
          $area:111
        },
        children:[]
      },
      ]
    },
    ]
  },
  ]
}